### ISSUE TITLE
Error when using contact_add (but likely other endpoints too)

### ISSUE THREAD

**Issue by mcmire** [mhenrixon/active_campaign#20]
When using the `contact_add` endpoint, even if I supply valid information as follows:

``` ruby
active_campaign_client = ActiveCampaign::Client.new
active_campaign_client.contact_add(
  "first_name" => "John",
  "email" => "john.smith@gmail.com",
  "p[999]" => 999,
)
```

then I get this response from the API:

```
{"result_code"=>0, "result_message"=>"Contact Email Address is not valid.", "result_output"=>"json", "results"=>[]}
```

I believe this is happening because the API expects this header to be present:

```
Content-Type: application/x-www-form-urlencoded
```

and it is not.

**Comment by mcmire** [comment]
I've got a quickfix for this here: https://github.com/mcmire/active_campaign/commit/a8b07178137a5e3e7df4863e9ed7369a0cfe0d5a. I have not tried running the tests as you have your API key hardcoded in spec_helper and I don't want to surprise you by changing any of the existing data. But it seemed to work for me locally.

**Comment by tlapuste** [comment]
Can you put that branch up as a pull-request @mcmire , took me forever to debug why I couldn't add or sync comments before I came across your post.

**Comment by mhenrixon** [comment]
Create a PR and I will get it merged properly. Don't worry about the API key or anything, I'll git this fixed over the next few days.

**Comment by mcmire** [comment]
Okay, here you go: https://github.com/mhenrixon/active_campaign/pull/21

**Comment by mhenrixon** [comment]
New version was released just now that contains this fix: https://github.com/mhenrixon/active_campaign/releases/tag/v0.1.15
