### ISSUE TITLE
contact_sync method raising SSL error

### ISSUE THREAD

**Issue by glm4** [mhenrixon/active_campaign#36]
Im getting the following error while trying to sync contacts. It previously worked fine and suddenly started to see this error:

`Excon::Error::Socket - SSL_connect returned=1 errno=0 state=SSLv3/TLS write client hello: tlsv1 alert protocol version (OpenSSL::SSL::SSLError) `

**Comment by glm4** [comment]
@mhenrixon It is weird because it was working before without verification, and I think it is ok otherwise we would need a certificate for `:peer` verification.
I saw [this notice](https://help.activecampaign.com/hc/en-us/articles/360003999019-TLS-1-0-1-1-Deprecation-FAQs) in the ActiveCampaing web site which is pretty recent and matches the dates when I started receiving error reports. They are dropping support for TLS v1.0 and v1.0. This gem is using 1.2 so I don't know what is the problem. I imagine they introduced a bug in their API v1 after this change.
Agree to update to V3 🙌

**Comment by mhenrixon** [comment]
Can you try monkey patch to:

```ruby
req.auth.ssl.ssl_version = :TLSv1_3
```

If it works, create a PR and I will get a fix released immediately @glm4

**Comment by glm4** [comment]
Let me check that 🙏

**Comment by glm4** [comment]
> Can you try monkey patch to:
> 
> ```ruby
> req.auth.ssl.ssl_version = :TLSv1_3
> ```
> 
> If it works, create a PR and I will get a fix released immediately @glm4

It says: 
```
ArgumentError - Invalid SSL version :TLSv1_3
Please specify one of [:TLSv1_2, :TLSv1_1, :TLSv1, :SSLv23]
```

I checked HTTPi and it gets the versions directly from  `OpenSSL::SSL::SSLContext`.
I don't know what to do next, maybe updating ruby to get a newer version of OpenSSL 🤔

**Comment by mhenrixon** [comment]
https://github.com/ruby/openssl/issues/207 seems like it is ruby version specific?

**Comment by mhenrixon** [comment]
Or maybe OS specific... I've got 99 problems and SSL is definitely one :(

**Comment by glm4** [comment]
> Or maybe OS specific... I've got 99 problems and SSL is definitely one :(

So you think using openssl 1.1.1 with the current version of the gem could work?

**Comment by mhenrixon** [comment]
> So you think using openssl 1.1.1 with the current version of the gem could work?

No idea, never really had any of these issues before. Maybe even bumping the installed `openssl` version would help? I am installing with `brew install openssl` for my iMac. 

Not sure if ruby would have to be recompiled on such a change though. I've read such things

**Comment by glm4** [comment]
Ok, pleas let me know. Thanks @mhenrixon !

**Comment by macmartine** [comment]
Does anyone have a workaround for this?

**Comment by arieliten** [comment]
using `req.auth.ssl.ssl_version = :TLSv1_2` worked for me

**Comment by glm4** [comment]
> using `req.auth.ssl.ssl_version = :TLSv1_2` worked for me

What do you mean? This configuration is already in `ActiveCampaing::Client`.

**Comment by mhenrixon** [comment]
@glm4 I’m pretty sure it has to do with the OpenSSL version installed on your machine then.

**Comment by glm4** [comment]
> @glm4 I’m pretty sure it has to do with the OpenSSL version installed on your machine then.

It is weird because I am having the issue in my dev maching(with LibreSSL 2.6.5) and in staging and production servers(Amazon EC2 RHLE with OpenSSL 1.0.2g  1 Mar 2016).
@arieliten Can you please post your openssl and ruby versions?

**Comment by arieliten** [comment]
@glm4 I had to monkey patch the `create_request` method to use the new version, and it worked for me.

```ruby
module ActiveCampaignExtensions
  module Client
    def create_request(method, api_method, options = {})
      req = HTTPI::Request.new(
        url: File.join(api_endpoint),
        headers: {
          'User-Agent' => user_agent,
          'Content-Type' => 'application/x-www-form-urlencoded'
        },
        query: query(method, api_method, options),
        body: body(method, api_method, options)
      )
      req.auth.ssl.verify_mode = :none
      # following line is the monkey patch that made the fix
      req.auth.ssl.ssl_version = :TLSv1_2
      req
    end
  end
end

# Opening the ActiveCampaign::Client class to remove the existing 'create_request' method and
# instead replace it with the version we wrote, that uses a different ssl_version
ActiveCampaign::Client.class_eval do
  remove_method :create_request
  include ActiveCampaignExtensions::Client
end
```

Also, my openssl version: `LibreSSL 2.2.7`

Hope it helps you

**Comment by glm4** [comment]
@arieliten Sorry, but what's the difference with [this line](https://github.com/mhenrixon/active_campaign/blob/d167c12fde63ad92a8b86171f3ea502f9cc0b1aa/lib/active_campaign/client.rb#L91)?

**Comment by glm4** [comment]
Never mind. Apparently I am using 0.1.15 and there is a new version 0.1.16 with the change to TLS 1.2.

**Comment by arieliten** [comment]
Yes @glm4 I have the same issue you had, since in the project I'm working on we are using version `0.1.14` which doesn't have the TLS 1.2 version, so I had to add myself. I'll see if I can upgrade the gem version too, but for some reason we're using a custom branch in our project and I still need to figure out why :)

**Comment by mhenrixon** [comment]
@arieliten could you attempt creating a PR from the branch you are using to see what differences there are? 

Maybe it is something that others could use too if there are any changes or customizations?
