### ISSUE TITLE
Using `Client` directly breaks following README examples

### ISSUE THREAD

**Issue by rylwin** [mhenrixon/active_campaign#74]
Hey there! I'm just starting down the path of an ActiveCampaign integration working against HEAD where I'm using `ActiveCampaign:::Client.new` and found I needed to add a couple extra options vs. what's shown in the README (which suggests I only need to set `api_url` and `api_token`).

```
    ActiveCampaign::Client.new(
      api_url: api_url,
      api_token: api_token,
      response_middleware: {},
      adapter: :net_http,
    )
```

If I don't set `response_middlewhere` to empty hash, I get a nil error when invoking `#none?` on nil. And if I don't specify an `adapter`, faraday can't make requests (error is "wrong constant name"). 

Would you be open to a PR that either:

- updates the README to show these other keys?
- sets a default `adapter` value / gracefully handles a nil `response_middleware` value?

Which of these approaches would be preferred? Let me know and I'd be happy to open a PR.

Thanks!

**Comment by mhenrixon** [comment]
I would not mind a PR at all, maybe with the adapter, it would be sufficient to use `Faraday.default_adapter` for the rest I have no idea.
